name: Process Chess Move

on:
  issues:
    types: [opened]

jobs:
  process-move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Move:')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-chess pillow stockfish pygithub requests
        
    - name: Install Stockfish engine
      run: |
        sudo apt-get update
        sudo apt-get install -y stockfish
        
    - name: Process chess move
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
        REPOSITORY: ${{ github.repository }}
      run: |
        python scripts/process_move.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || (git commit -m "Update chess game after move by ${{ github.event.issue.user.login }}" && git push)
